[project]
name = "a-maze-ing"
version = "0.1.0"
description = "Maze builder, solver of the maze and visual representation"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "eel-kerc"},
    {name = "lebeyssa"}
]
dependencies = [

]

[tool.poetry]
packages = [{include = "srcs"}]

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"